# Generated by Django 4.1.7 on 2023-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsindexpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='item_type',
            field=models.CharField(blank=True, default='News', max_length=5, null=True),
        ),
    ]
