# Generated by Django 4.1.7 on 2023-04-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspage_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='feature_image',
            new_name='feature_image_570x400',
        ),
    ]
