# Generated by Django 4.1.7 on 2023-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_feature_image_newspage_feature_image_570x400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
