# Generated by Django 4.1.7 on 2023-04-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('news', '0005_newspage_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsindexpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='newsindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='feature_image_570x400',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='item_type',
            field=models.CharField(blank=True, default='News', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newspagegalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
    ]
