# Generated by Django 4.2.1 on 2023-05-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexpage',
            old_name='banner_backgroun_image',
            new_name='banner_background_image',
        ),
    ]
