# Generated by Django 4.1.7 on 2023-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='item_type',
            field=models.CharField(blank=True, default='Projects', max_length=5, null=True),
        ),
    ]
